name: Build

on:
  push:
    branches: [ nextgen ]
  pull_request:
    branches: [ nextgen ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Setting up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
    
      - name: Grant ALL permissions to theme
        run: sudo chmod -R 777 theme
      
      - name: Setup and build
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: genSources build
      
      - name: Run
        run: |
          function gradleprop {
              grep "${1}" gradle.properties|cut -d'=' -f2
          }
          export LB_VERSION=$(gradleprop 'mod_version')
          export MINECRAFT_VERSION=$(gradleprop 'minecraft_version')
          export LOADER_VERSION=$(gradleprop 'loader_version')
          export FABRICAPI_VERSION=$(gradleprop 'fabric_version')
          export KOTLIN_VERSION=$(gradleprop 'kotlin_version')
          export FABRIC_KOTLIN_VERSION=$(gradleprop 'fabric_kotlin_version')
          echo Version: $LB_VERSION, Minecraft: $MINECRAFT_VERSION
          cd build/libs
          export JAR=$(find . -regex '.*liquidbounce-[0-9|.]*\.jar')
          cp $JAR zip/liquidbounce.jar
          cd zip
          zip -r liquidbounce.zip *
          md5sum liquidbounce.zip
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with: 
         name: a
         path: .
        
